### ISSUE TITLE
Form Input get values

### ISSUE THREAD

**Issue by mbantwerpes** [mbantwerpes/react-tailwind-storybook#1]
Im Folder Pages ist die Page `BuildingComponent` die die Komponente `ModalCreateBuildingComponent` als Child hat. In `ModalCreateBuildingComponent` ist eine Form drin die mehrere Inputs hat. Jetzt will ich `onSubmit` die Values der Inputs/Textarea haben und in der `BuildingComponent` dem State hinzufügen. Die Inputs sind controlled components. Muss ich hier jetzt auch den state aus den Inputs hoch ziehen und in der `ModalCreateBuildingComponent` abbilden? Das wäre ziemlich viel state der ausgelagert wird und dann hätte die Input-Komponente ja garkeinen State mehr.

**Comment by dbrenzis** [comment]
Der State des Formulares bliebt in der Komponente ModalCreateBuildingComponent.
Wenn du beim onSubmit keinen Request durchführen möchtest, dann gibt einfach eine handleSubmit Funktion an die FormularKomponente mit dem Type:
(newBuilding:BuildingType) => void oder boolean oder Promise<boolean> oder was auch immer du möchtest:D
